# permissions to do edit disks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disk-editor-role
rules:
- apiGroups:
  - core.api.onmetal.de
  resources:
  - disks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.api.onmetal.de
  resources:
  - disks/status
  verbs:
  - get
  - patch
  - update
