# permissions for end users to view disks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disk-viewer-role
rules:
- apiGroups:
  - storage.onmetal.de
  resources:
  - disks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - disks/status
  verbs:
  - get
