# permissions for end users to edit ipamranges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipamrange-editor-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - ipamranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - ipamranges/status
  verbs:
  - get
