# permissions for end users to edit keypairs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keypair-editor-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - keypairs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - keypairs/status
  verbs:
  - get
