# permissions for end users to view keypairs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keypair-viewer-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - keypairs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - keypairs/status
  verbs:
  - get
