# permissions to do viewer loadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadbalancer-viewer-role
rules:
- apiGroups:
  - core.api.onmetal.de
  resources:
  - loadbalancers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.api.onmetal.de
  resources:
  - loadbalancers/status
  verbs:
  - get
