# permissions to do edit machines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-editor-role
rules:
- apiGroups:
  - core.api.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.api.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
