# permissions for end users to view reservedips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reservedip-viewer-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - reservedips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - reservedips/status
  verbs:
  - get
