# permissions for end users to edit reservedips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reservedip-editor-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - reservedips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - reservedips/status
  verbs:
  - get
