
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses/finalizers
  verbs:
  - update
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.onmetal.de
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - scopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.onmetal.de
  resources:
  - scopes/finalizers
  verbs:
  - update
- apiGroups:
  - core.onmetal.de
  resources:
  - scopes/status
  verbs:
  - get
  - patch
  - update
