# permissions for end users to view routingdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routingdomain-viewer-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - routingdomains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - routingdomains/status
  verbs:
  - get
