# permissions for end users to edit routingdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routingdomain-editor-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - routingdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - routingdomains/status
  verbs:
  - get
