# permissions for end users to view securitygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: securitygroup-viewer-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - securitygroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - securitygroups/status
  verbs:
  - get
