# permissions for end users to view snapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshot-viewer-role
rules:
- apiGroups:
  - storage.onmetal.de
  resources:
  - snapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - snapshots/status
  verbs:
  - get
