# permissions for end users to edit sshpublickeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sshpublickey-editor-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - sshpublickeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - sshpublickeys/status
  verbs:
  - get
