# permissions for end users to view sshpublickeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sshpublickey-viewer-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - sshpublickeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - sshpublickeys/status
  verbs:
  - get
