# permissions for end users to edit subnetips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subnetip-editor-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - subnetips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - subnetips/status
  verbs:
  - get
