# permissions for end users to edit volumeattachments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumeattachment-editor-role
rules:
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeattachments/status
  verbs:
  - get
