# permissions for end users to view volumeattachments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumeattachment-viewer-role
rules:
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeattachments/status
  verbs:
  - get
