apiVersion: compute.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: machine-sample
spec:
  hostname: myhost
  machineClass:
    name: x3.xlarge
  machinePool:
    name: default
  image: myimage_repo_location
  sshPublicKeys:
    - name: mykey
  interfaces:
    - name: myinterface
      priority: 0 # optional
      target:
        name: mySubnetName
  securityGroups:
    - name: mysecgroup1
  volumeClaims:
    - name: rootdisk # first disk is root disk
      retainPolicy: DeleteOnTermination
      priority: 0 # optional
      storageClass:
        name: slow
      size: 100Gi
  ignition: |
    myIgnitionYAML
  efiVars:
    - name: PK
      uuid: 8be4df61-93ca-11d2-aa0d-00e098032b8c
      value: pki.Gardenlinux.io/kernel.crt