apiVersion: core.onmetal.de/v1alpha1
kind: Region
metadata:
  name: region-sample
spec:
  location: Frankfurt
  availabilityZones:
  - zone1
  - zone2
#status:
#  state: Active
#  message: "Up and runnning"
#  availabilitzZones:
#  - name: zone1
#    state: Active
#    message: "Up and running"
#  - name: zone2
#    state: Offline
#    message: "Down for maintanance"
