apiVersion: storage.onmetal.de/v1alpha1
kind: Volume
metadata:
  name: volume-sample
spec:
  storageClass:
    name: storageclass-sample
  storagePool:
    name: storagepool-sample
  resources:
    storage: 100Gi
